[tool.poetry]
name = "tg-utility-bot"
version = "0.1.0"
description = "Telegram bot for random purpose."
authors = ["odhako <odhako@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
